server:
  port: 8082
  servlet:
    context-path: /mybatis
    encoding:
      charset: UTF-8
spring:
  application:
    name: mybatis
  datasource:
    url: jdbc:postgresql://localhost:5432/mybatis
    driver-class-name: org.postgresql.Driver
    username: kocesat
    password: Ankara06
  messages:
    fallback-to-system-locale: false
    basename: messages, messages/info, messages/error
  quartz:
    job-store-type: jdbc
    scheduler-name: mybatis_demo
    properties:
      org:
        quartz:
          jobStore:
            tablePrefix: QRTZ_
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
            misfireThreshold: 5000
            useProperties: true
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 5
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 120000
# Mybatis configuration
mybatis:
  mapper-locations: classpath:mapper/*
# Normally, we need to write package name for each class written
#  in xml mapper config in MyBatiss. With this set, we do not need to write
#  package names to all classes
  type-aliases-package: com.kocesat.mybatisdemo.model**
  configuration:
# class fields'names to sql column name
# firstName --> FIRST_NAME
    map-underscore-to-camel-case: true